create table if not exists public.signal_deliveries (
  id bigint generated by default as identity primary key,
  delivery_type text not null check (delivery_type in ('news', 'market')),
  delivery_key text not null,
  platform text not null check (platform in ('telegram', 'discord')),
  status text not null check (status in ('sent', 'failed', 'skipped')),
  title text,
  source text,
  url text,
  category text,
  relevance_score integer not null default 0,
  message text,
  error_message text,
  payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists signal_deliveries_lookup_idx
  on public.signal_deliveries (delivery_type, delivery_key, platform, status);

create index if not exists signal_deliveries_sent_at_idx
  on public.signal_deliveries (delivery_type, sent_at desc);

create unique index if not exists signal_deliveries_sent_unique_idx
  on public.signal_deliveries (delivery_type, delivery_key, platform)
  where status = 'sent';

alter table public.signal_deliveries enable row level security;

create policy "service role can manage signal deliveries"
  on public.signal_deliveries
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
